### ISSUE TITLE
pull access denied for mds_slurm

### ISSUE THREAD

**Issue by TheLexoPlexx** [DanBmh/deepspeech-german#1]
When trying to execute `docker build -t deep_speech_german deepspeech-german/` after cloning `https://github.com/DanBmh/deepspeech-german.git`.

Any suggestions on this?

**Comment by Devirex** [comment]
Same here, seems like mds_slurm is not available via Docker Hub.

**Comment by DanBmh** [comment]
Sorry for my late response, I missed the issue notification.

The container images are not uploaded somewhere, you will have to build them yourself.
The Dockerfile for mds_slurm is this here: slurm/Dockerfile_slurm

But you can use the default Dockerfile from DeepSpeech too.
(I had some problems with gpu detection on a dgx, thats why i used the mds_slurm image)
