### ISSUE TITLE
TVSMC model checkpoint

### ISSUE THREAD

**Issue by tanujjain** [DanBmh/deepspeech-german#2]
Hi,

Thanks for the pretrained model (deepspeech 0.7.0a2). 
Questions:
1. The link to the checkpoint of the model is broken. Could you please have a look? 
2. The link description for checkpoint says (currently out of date), but the model file is also provided for this (which works). What does being out of date mean? Will it not work if one tries to use the checkpoint?

**Comment by lagidigu** [comment]
Would like to thank you as well for the pretrained model. It would be really really awesome to have the checkpoint files as well, then we can expand on it! :)

Cheers!

**Comment by DanBmh** [comment]
Sorry for my late response, I missed the issue notification.

1. I now have updated the link. 
2. I wanted to say that the link is out of date (I knew the upload would be autodeleted after some time, but i wanted to train a new model before anyway. Then a new project came in my way...)  
So you can still use the checkpoint, and it should be still compatible with the current DeepSpeech master.
